### PR TITLE
Performance audit

### PR DESCRIPTION
**Pull request by jorgeabrahan**
✅ Performance audit the vets' database
✅ Create a non-claustered index database for the visits table ordering the animals_id ascending
✅ Query the animals id from visits with the indexed database to verify a reduced time
✅ Create a non-claustered index database for the visits table ordering the vets_id ascending
✅ Query vets table to check if time has decreased
✅ Create a non-claustered index database for the owners' table
✅ Query owners table to check if time has decreased

#### Before performance audit 

query-1-before

#### After performance audit 

query-1-after

#### Before performance audit 
before-2nd

#### After performance audit 
after-2nd

#### Before performance audit 
query-3-before

#### After performance audit 
query-3-after

### CODE REVIEW

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @jorgeabrahan @biruk-bereka , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] The execution time in the screenshots BEFORE is not significantly lower than 1 sec (1000ms) and I suggest running the populate database query a few times more as described in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_performance_audit.md#:~:text=4%20Depening%20on,bigger%20than%201000ms.). 👍🏾 😄

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @jorgeabrahan and @biruk-bereka   :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.



 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: Good PR


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As suggested by the previous reviewer, The execution time for the query `EXPLAIN ANALYZE SELECT * FROM owners where email = 'owner_18327@mail.com';` and `EXPLAIN ANALYZE SELECT * FROM visits where vet_id = 2` is not significantly lower than 1 sec (1000ms) as you can see in the screenshot of your PR. :smile: I suggest running the populate database query a few times more as described in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_performance_audit.md#:~:text=4%20Depening%20on,bigger%20than%201000ms.) and take a screen of a good result with execution time less than 1 sec (1000ms) :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by biruk-bereka** [comment]
@Owusu-Desmond the screenshot above is before and after for each queries. 

# For example: EXPLAIN ANALYZE SELECT * FROM owners where email = '[owner_18327@mail.com](mailto:owner_18327@mail.com)';

### Before performance audit: Execution time = 1957.776ms  
### After  performance audit: Execution time = 0.802ms 

Screenshot (46)

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @jorgeabrahan @biruk-bereka   , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.




 ## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Good job on the implementing the changes but it not over yet as suggested by the previous reviewer, The execution time for the query `EXPLAIN ANALYZE SELECT * FROM visits where vet_id = 2 ` is not significantly lower than 1 sec (1000ms) as you can see in the screenshot of your PR. 😄 I suggest running the populate database query a few times more as described in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_performance_audit.md#:~:text=4%20Depening%20on,bigger%20than%201000ms.) and take a screen of a good result with execution time less than 1 sec (1000ms)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by uwadonat — APPROVED** [review]
## Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Detailed pull request message ✔️
- Clear screenshot of the results ✔️
- Good commit history ✔️
thanks-awesome


# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
